markdown: kramdown
kramdown:
  math_engine: mathjax
  math_engine_opts:
    preview: true

title: SDP bounds on quantum codes
url: "https://huberfe.github.io/SDP-code-bounds"


nav:
 - name: "Home"
   link: "index"
 - name: "SDP bounds"
   link: "sdp"
 - name: "QMDS bounds"
   link: "qmds"
